name: Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install PHP
      run: sudo apt-add-repository ppa:ondrej/php -y && sudo apt update && sudo apt install php8.2 -y

    - name: Validate composer.json and composer.lock
      run: composer validate --strict || echo 'Validation failed'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
