name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    if: github.repository_owner == 'virtual-designer'
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.15.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './composer.json'
          git-user-name: "Conventional Release Action"
          git-user-email: rakinar2@onesoftnet.eu.org

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

